### ISSUE TITLE
A render of a StructuredNavigation should be easily customizable

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#3]
### Implementation
 - [ ] A developer is able to register their own format
 - [ ] A system administrator is able to set the default format via `$wgStructuredNavigationDefaultFormat`
 - [ ] The `mw-navigation` should silently fallback to the default format when:
     - [ ] the format passed by the user is not in the list of registered formats
     - [ ] no format is passed by the user
 - [ ] There is a machine-readable way in the DOM to determine the given format (if the format is 'table', the navigation would have `data-structurednavigation-format="table"` applied)
 - [ ] The list of registered navigation formats is exposed to the end-user on the wiki, via Special:RegisteredNavigationFormats

### Documentation
 - [ ] There is supplied documentation for:
     - [ ] The `format` attribute for the `mw-navigation` tag
     - [ ] Creating and registering a custom formatter

**Comment by SamanthaNguyen** [comment]
Here's the set of styles I made specifically made for the sidebar. When I was experimenting, I commented out the two other modules that's seen in ParserFirstCallInitHandler and registered a different, custom RL module for the sidebar styles.

The styles I wrote were pretty quickly written so it's more of a proof of concept, but it should probably be pretty stable (maybe?) _[citation needed]_
```css
.mw-structurednav-navigation-container {
	float: right;
	background: #f9f9f9;
	border: 1px solid #aaa;
	padding: 0.2em;
	width: 22em;
	font-size: 88%;
}
	
.mw-structurednav-header .mw-structurednav-header-title {
	border: 0;
	font-family: 'Arial', sans-serif;
	font-size: 19px;
	font-weight: 700;
	text-align: center;
	padding: .75em 0.25em 0.25em;
	margin: 0;
}
	
.mw-structurednav-group {
	padding: .5em 0;
}
	
.mw-structurednav-group-title {
	text-align: center;
	font-size: 16px;
}
	
.mw-structurednav-group-content {
	text-align: left;
	padding: 0;
	margin: 0;
}
```
